### PR TITLE
Login button and stack navigation

### PR DESCRIPTION
**Pull request by mmislam101**
Stack navigation isn't what we'll end up using, but I haven't learned about all the other options. Later based on state we'll display one or the other, but leave that to another PR to implement.

### CODE REVIEW

**Comment by ahmednkhan24** [comment]
Thanks for getting us started. 

One convention to follow is that all React components should start with a capital letter, so I would change `home.tsx` and `login.tsx` to `Home.tsx` and `Login.tsx`.

Also something with one of the new dependencies is breaking the unit test. 

Other than that I like it.

**Comment by mmislam101** [comment]
> Thanks for getting us started.
> 
> One convention to follow is that all React components should start with a capital letter, so I would change `home.tsx` and `login.tsx` to `Home.tsx` and `Login.tsx`.
> 
> Also something with one of the new dependencies is breaking the unit test.
> 
> Other than that I like it.

Updated the names. The fix for the test error was not easy to fix =/

**Comment by ahmednkhan24** [comment]
Oh man, I didn't even catch that! Thank you for digging into it lol and my apologies for not initially having that

**Review by ahmednkhan24 — APPROVED** [review]

**Comment by mmislam101** [comment]
> Oh man, I didn't even catch that! Thank you for digging into it lol and my apologies for not initially having that

no apologies necessary. Just whew! didn't realize these tests were UI automation tests and requires mocking that deep.

**Pull request merged**
